name: main

on:
    push:
        branches:
            - '*'

jobs:
    commitlint:
        name: Lint Commit Messages
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v5

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: commitlint
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: 'Prepare: Bump version and push tag'
              id: changelog
              uses: sirPixieJerry/conventional-changelog-action@releases/v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-on-empty: 'true'
                  output-file: 'false'
                  git-message: 'chore(release): {version}'
                  tag-prefix: 'v'
                  version-file: gradle.properties
                  version-path: mod_version
            - name: 'Release: Create Release on Github'
              if: ${{ steps.changelog.outputs.skipped != 'true' && steps.changelog.outputs.tag != ''}}
              id: create_release
              uses: softprops/action-gh-release@v1
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                tag_name: ${{ steps.changelog.outputs.tag }}
                body: ${{ steps.changelog.outputs.clean_changelog }}
                draft: false
                prerelease: false